CREATE TABLE GROUPS
(
    ID_GROUP     NUMBER(3)              NOT NULL,
    NOM_GROUP      VARCHAR2(25)           NOT NULL,
    DESCRIPTION_GROUP        VARCHAR2(100),
    IMG_GROUP VARCHAR2(1000),
    CONSTRAINT PK_GROUP PRIMARY KEY (ID_GROUP)
);


CREATE TABLE CONTACTS 
(
  ID_CTC NUMBER(6, 0) NOT NULL 
, CIV_CTC NUMBER(1, 0) NOT NULL 
, NOM_CTC VARCHAR2(2 BYTE) NOT NULL 
, PRENOM_CTC VARCHAR2(25 BYTE) 
, ADDR1_CTC VARCHAR2(50 BYTE) 
, ADDR2_CTC VARCHAR2(50 BYTE) 
, CP_CTC NUMBER(5, 0) 
, VILLE_CTC VARCHAR2(25 BYTE) 
, TEL_CTC NUMBER(10, 0) 
, FAX_CTC NUMBER(10, 0) 
, MAIL_CTC VARCHAR2(100 BYTE) 
, TYPE_CTC NUMBER(1, 0) NOT NULL 
, DESCRIPTION_CTC VARCHAR2(100 BYTE) 
, FONCTION_CTC VARCHAR2(20 BYTE) 
, IMG_CTC VARCHAR2(1000 BYTE) 
, CREA_CTC DATE 
, UPD_CTC DATE 
, CONSTRAINT PK_USER PRIMARY KEY (ID_CTC)
  USING INDEX (
      CREATE UNIQUE INDEX PK_USER ON CONTACTS (ID_CTC ASC) 
      LOGGING 
      TABLESPACE GTN_CONTACT_DEFAULT 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
COMMENT ON TABLE CONTACTS IS 'contacts existant en base';



CREATE TABLE APPARTIENT 
(
  ID_CONTACT NUMBER NOT NULL 
, ID_GROUP NUMBER NOT NULL 
, ADD_DATE DATE 
);
