-- DROP DATABASE IF EXISTS GTN_CONTACT;
CREATE DATABASE IF NOT EXISTS GTN_CONTACTS;

USE GTN_CONTACTS;

DROP TABLE IF EXISTS APPARTIENT;
CREATE TABLE APPARTIENT (
    ID_CONTACT 			INT(6) 			NOT NULL,
    ID_GROUP 			INT(6) 			NOT NULL,
    DATE_AJOUT 			DATE 			NOT NULL,
    PRIMARY KEY (ID_CONTACT, ID_GROUP)
);

DROP TABLE IF EXISTS CONTACTS;
CREATE TABLE CONTACTS (
    ID_CONTACT			INT(6)			NOT NULL	AUTO_INCREMENT,
    CIV_CONTACT			INT(1)			NOT NULL,
    NOM_CONTACT			VARCHAR(25)		NOT NULL,
    PRENOM_CONTACT		VARCHAR(25)		,
    ADDR1_CONTACT		VARCHAR(50)		,
    ADDR2_CONTACT		VARCHAR(50)		,
    CP_CONTACT			VARCHAR(6)		,
    VILLE_CONTACT		VARCHAR(25)		,
    TEL_CONTACT			INT(10)			,
    FAX_CONTACT			INT(10)			,
    MAIL_CONTACT		VARCHAR(100)	,
    DESCRIPTION_CONTACT VARCHAR(200)	,
    FONCTION_CONTACT	VARCHAR(50)		,
    IMG_CONTACT			VARCHAR(1000)	,
    DATE_CREA_CONTACT	DATE			NOT NULL DEFAULT CURRENT_DATE,
    DATE_MODIF_CONTACT	DATE			NOT NULL ON UPDATE CURRENT_DATE,
    PRIMARY KEY (ID_CONTACT)
);

DROP TABLE IF EXISTS GROUPS;
CREATE TABLE GROUPS (
    ID_GROUP			INT(6)			NOT NULL	AUTO_INCREMENT,
    NOM_GROUP			VARCHAR(25)		NOT NULL,
    DESCRIPTION_GROUP	VARCHAR(200)	,
    IMG_GROUP			VARCHAR(1000)	,
	DATE_CREA_GROUP		DATE			NOT NULL DEFAULT CURRENT_DATE,
    DATE_MODIF_GROUP	DATE			NOT NULL ON UPDATE CURRENT_DATE,
    PRIMARY KEY (ID_GROUP)
);

DROP TABLE IF EXISTS PARTAGE;
CREATE TABLE PARTAGE (
    ID_EXPEDITEUR		INT(6)			NOT NULL,
    ID_DESTINATAIRE		INT(6)			NOT NULL,
    ID_CONTACT			INT(6)			NOT NULL,
    READ_ONLY			VARCHAR(1)		NOT NULL,
    PRIMARY KEY (ID_EXPEDITEUR, ID_DESTINATAIRE, ID_CONTACT)
);

DROP TABLE IF EXISTS RIGHTS;
CREATE TABLE RIGHTS (
    ID_RIGHT			INT(6)			NOT NULL	AUTO_INCREMENT,
    DESCRIPTION_RIGHT	VARCHAR(50)		NOT NULL,
    PRIMARY KEY (ID_RIGHT)
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    ID_USER				INT(6)			NOT NULL	AUTO_INCREMENT,
    MAIL_USER			VARCHAR(200)	NOT NULL,
    MDP_USER			VARCHAR(25)		NOT NULL,
	ID_RIGHT			INT(6)			NOT NULL,
    PRIMARY KEY (ID_USER)
);

ALTER TABLE APPARTIENT 	ADD CONSTRAINT FK_CONTACTS_ID_CONTACT 		FOREIGN KEY (ID_CONTACT) 
REFERENCES CONTACTS(ID_CONTACT) 	ON DELETE RESTRICT 		ON UPDATE RESTRICT;
ALTER TABLE APPARTIENT 	ADD CONSTRAINT FK_CONTACTS_ID_GROUP 		FOREIGN KEY (ID_GROUP) 
REFERENCES GROUPS(ID_GROUP) 		ON DELETE RESTRICT 		ON UPDATE RESTRICT;

ALTER TABLE PARTAGE 	ADD CONSTRAINT FK_PARTAGE_ID_EXPEDITEUR 	FOREIGN KEY (ID_EXPEDITEUR) 
REFERENCES USERS(ID_USER) 			ON DELETE RESTRICT 		ON UPDATE RESTRICT; 
ALTER TABLE PARTAGE 	ADD CONSTRAINT FK_PARTAGE_ID_DESTINATAIRE 	FOREIGN KEY (ID_DESTINATAIRE) 
REFERENCES USERS(ID_USER) 			ON DELETE RESTRICT 		ON UPDATE RESTRICT; 
ALTER TABLE PARTAGE 	ADD CONSTRAINT FK_PARTAGE_ID_CONTACT 		FOREIGN KEY (ID_CONTACT) 
REFERENCES CONTACTS(ID_CONTACT) 	ON DELETE RESTRICT 		ON UPDATE RESTRICT;

ALTER TABLE USERS 		ADD CONSTRAINT FK_USERS_ID_RIGHT 			FOREIGN KEY (ID_RIGHT) 
REFERENCES RIGHTS(ID_RIGHT) 		ON DELETE RESTRICT 		ON UPDATE RESTRICT;